Casters for strided_views, array_adaptor, and tensor_adaptor
xtensor-stack/xtensor-python pull request #243
Opened 2020-11-23 19:12 UTC by PerretB

This PR partly solves #130 by adding pybind11 type casters for ```strided_views``` and ```array/tensor_adapters```.

As for ```xarrays``` and ```xtensors```, those objects are casted to ```ndarray``` and do not use any proxy object (such as ```pyarray``` or ```pytensor```): I did a bit of refactoring to put all those casters in a dedicated file. 

Memory management becomes of course trickier with such objects.  I have the impression that what is done in ```xtensor_type_caster_base``` to handle return value policies is generic enough to fit these cases but I am not totally sure. I tried to demonstrate critical cases in the test file (cpp main). The tests *validating* the correctness of the memory management (keep alive policies) are perhaps not very interesting for regression detection has they focus on pybind11 mechanism  rather than xtensor_python and could probably be removed.

2020-11-24 09:28 UTC, PerretB commented
It seems that the CI configurations are outdated:

- for unix  it looks like a python interpreters mismatch 
- for windows, I guess that the latest version of gtest is not compatible with VS 2015

2020-11-27 07:32 UTC, JohanMabille commented
I'm making a pass on the whole stack to fix all the CI issues (among them, migrating from travis to Azure), it takes time but eventually we'll get there.

2020-11-30 08:26 UTC, JohanMabille commented
> The tests validating the correctness of the memory management (keep alive policies) are perhaps not very interesting for regression detection has they focus on pybind11 mechanism rather than xtensor_python and could probably be removed.

I think we should keep them, this would help detecting any change or regression in pybind11. Even if pybind11 is well tested, having tests specific to our use case is a good thing.

2020-11-30 08:27 UTC, JohanMabille requested changes

2020-11-30 08:27 UTC, JohanMabille commented on include/xtensor-python/pynative_casters.hpp
> +#define PYNATIVE_CASTERS_HPP
This file should be added to the header list in `CMakeLists.txt` so that it gets installed when installing `xtensor-python`.

2020-11-30 15:42 UTC, JohanMabille approved these changes

2020-11-30 15:42 UTC, merged