ignore unused parameter 'buf' warning
xtensor-stack/xtensor-python pull request #283
Opened 2022-09-20 14:00 UTC by peter-urban

I included <xtensor-python/xtensor_type_caster_base.hpp> into my code to let pybind11 automatically convert xtensor xarrays to numpy arrays.

 However I get two "-wunused-parameter warnings" which seem to be very easy to fix :-)

2022-09-20 14:19 UTC, peter-urban commented
Not sure, but the appveyor fail seems to be unrelated to my pull request?

2023-03-02 16:26 UTC, tdegeus commented
Thanks! You could also just remove the name `buf` from the argument. Is there any reason to keep it?

2023-03-08 13:41 UTC, peter-urban commented
I don't understand the code well enough to propose such a change. 

To me this looks like a dummy function (just just returns true) to implement a sort of interface (but I don't know which one).
Removing the variable could thus break this interface. 

Do you have more insights into the code? Because if you say that we can remove the variable, it is of cause not problem for me to adapt the PR :-)

2023-03-09 14:45 UTC, tdegeus requested changes
I meant this

2023-03-09 14:45 UTC, tdegeus commented on include/xtensor-python/xtensor_type_caster_base.hpp
>              }
```suggestion
            static bool run(const B&)
            {
                return true;
            }
```

2023-03-10 08:28 UTC, peter-urban commented on include/xtensor-python/xtensor_type_caster_base.hpp
>              }
Aah nice, I was not aware that this is valid c++ code actually :-D

2023-03-10 09:12 UTC, merged